spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test-db

logging:
    level:
      org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
      org.springframework.data.mongodb.core.MongoTemplate: DEBUG

